name: Grade-data-reload-API
run-name: Data-API is reloading......
on:
  push:
  schedule:
    - cron: "* * 1 * *"
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 main.py
 
